db:
  dsn: postgres://admin:admin@5Gdb:5432/hust?sslmode=disable
  driver: postgres

api:
  addr: ":8080"

auth:
  secret-key: "opensource"
  username: "admin"
  password: "admin"

rpc:
  addr: "127.0.0.1:8000"