# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncore.proto\x12\x02pb\"#\n\x0e\x41nalyseRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\"f\n\x0f\x41nalyseResponse\x12\x13\n\x0b\x61ll_account\x18\x01 \x01(\x05\x12\x0e\n\x06level0\x18\x02 \x01(\x05\x12\x0e\n\x06level1\x18\x03 \x01(\x05\x12\x0e\n\x06level2\x18\x04 \x01(\x05\x12\x0e\n\x06level3\x18\x05 \x01(\x05\"!\n\x0cTrainRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\" \n\rTrainResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\"\n\tDatainput\x12\x15\n\rclocationinfo\x18\x01 \x01(\t\"2\n\x0c\x41lertRequest\x12\"\n\x0b\x64\x61tarequest\x18\x01 \x03(\x0b\x32\r.pb.Datainput\"#\n\nDataoutput\x12\x15\n\rclocationinfo\x18\x01 \x01(\t\"5\n\rAlertResponse\x12$\n\x0c\x64\x61taresponse\x18\x01 \x03(\x0b\x32\x0e.pb.Dataoutput2\x9c\x01\n\x04\x63ore\x12\x34\n\x07\x41nalyse\x12\x12.pb.AnalyseRequest\x1a\x13.pb.AnalyseResponse\"\x00\x12.\n\x05Train\x12\x10.pb.TrainRequest\x1a\x11.pb.TrainResponse\"\x00\x12.\n\x05\x41lert\x12\x10.pb.AlertRequest\x1a\x11.pb.AlertResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ANALYSEREQUEST._serialized_start=18
  _ANALYSEREQUEST._serialized_end=53
  _ANALYSERESPONSE._serialized_start=55
  _ANALYSERESPONSE._serialized_end=157
  _TRAINREQUEST._serialized_start=159
  _TRAINREQUEST._serialized_end=192
  _TRAINRESPONSE._serialized_start=194
  _TRAINRESPONSE._serialized_end=226
  _DATAINPUT._serialized_start=228
  _DATAINPUT._serialized_end=262
  _ALERTREQUEST._serialized_start=264
  _ALERTREQUEST._serialized_end=314
  _DATAOUTPUT._serialized_start=316
  _DATAOUTPUT._serialized_end=351
  _ALERTRESPONSE._serialized_start=353
  _ALERTRESPONSE._serialized_end=406
  _CORE._serialized_start=409
  _CORE._serialized_end=565
# @@protoc_insertion_point(module_scope)
