#rpc:
#	python3 -m grpc_tools.protoc -Ipb --pyi_out=. --python_out=. --grpc_python_out=. pb/core.proto
rpc:
	python -m grpc_tools.protoc -Ipb --pyi_out=. --python_out=. --grpc_python_out=. pb/core.proto


