// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pb/core.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clogid        int32  `protobuf:"varint,1,opt,name=clogid,proto3" json:"clogid,omitempty"`              // 日志ID
	Calarmcode    int32  `protobuf:"varint,2,opt,name=calarmcode,proto3" json:"calarmcode,omitempty"`      // 告警代码
	Cneid         int32  `protobuf:"varint,3,opt,name=cneid,proto3" json:"cneid,omitempty"`                // 网元ID
	Calarmlevel   int32  `protobuf:"varint,4,opt,name=calarmlevel,proto3" json:"calarmlevel,omitempty"`    // 设备告警等级
	Coccurutctime string `protobuf:"bytes,5,opt,name=coccurutctime,proto3" json:"coccurutctime,omitempty"` // 告警时间
	Clocationinfo string `protobuf:"bytes,6,opt,name=clocationinfo,proto3" json:"clocationinfo,omitempty"` // 设备定位信息
	Clineport     string `protobuf:"bytes,7,opt,name=clineport,proto3" json:"clineport,omitempty"`         // 线路端口字符串
}

func (x *DataStruct) Reset() {
	*x = DataStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_core_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataStruct) ProtoMessage() {}

func (x *DataStruct) ProtoReflect() protoreflect.Message {
	mi := &file_pb_core_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataStruct.ProtoReflect.Descriptor instead.
func (*DataStruct) Descriptor() ([]byte, []int) {
	return file_pb_core_proto_rawDescGZIP(), []int{0}
}

func (x *DataStruct) GetClogid() int32 {
	if x != nil {
		return x.Clogid
	}
	return 0
}

func (x *DataStruct) GetCalarmcode() int32 {
	if x != nil {
		return x.Calarmcode
	}
	return 0
}

func (x *DataStruct) GetCneid() int32 {
	if x != nil {
		return x.Cneid
	}
	return 0
}

func (x *DataStruct) GetCalarmlevel() int32 {
	if x != nil {
		return x.Calarmlevel
	}
	return 0
}

func (x *DataStruct) GetCoccurutctime() string {
	if x != nil {
		return x.Coccurutctime
	}
	return ""
}

func (x *DataStruct) GetClocationinfo() string {
	if x != nil {
		return x.Clocationinfo
	}
	return ""
}

func (x *DataStruct) GetClineport() string {
	if x != nil {
		return x.Clineport
	}
	return ""
}

// 传入的文件内容
type AnalyseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*DataStruct `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *AnalyseRequest) Reset() {
	*x = AnalyseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_core_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalyseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyseRequest) ProtoMessage() {}

func (x *AnalyseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_core_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyseRequest.ProtoReflect.Descriptor instead.
func (*AnalyseRequest) Descriptor() ([]byte, []int) {
	return file_pb_core_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyseRequest) GetData() []*DataStruct {
	if x != nil {
		return x.Data
	}
	return nil
}

// 返回初步分析结果
type AnalyseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllAccount int32 `protobuf:"varint,1,opt,name=all_account,json=allAccount,proto3" json:"all_account,omitempty"` // 返回数据的所有值
	Level0     int32 `protobuf:"varint,2,opt,name=level0,proto3" json:"level0,omitempty"`                           // 提示数据的个数
	Level1     int32 `protobuf:"varint,3,opt,name=level1,proto3" json:"level1,omitempty"`                           // 次要数据的个数
	Level2     int32 `protobuf:"varint,4,opt,name=level2,proto3" json:"level2,omitempty"`                           // 主要数据的个数
	Level3     int32 `protobuf:"varint,5,opt,name=level3,proto3" json:"level3,omitempty"`                           // 紧急数据的个数
}

func (x *AnalyseResponse) Reset() {
	*x = AnalyseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_core_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalyseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyseResponse) ProtoMessage() {}

func (x *AnalyseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_core_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyseResponse.ProtoReflect.Descriptor instead.
func (*AnalyseResponse) Descriptor() ([]byte, []int) {
	return file_pb_core_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyseResponse) GetAllAccount() int32 {
	if x != nil {
		return x.AllAccount
	}
	return 0
}

func (x *AnalyseResponse) GetLevel0() int32 {
	if x != nil {
		return x.Level0
	}
	return 0
}

func (x *AnalyseResponse) GetLevel1() int32 {
	if x != nil {
		return x.Level1
	}
	return 0
}

func (x *AnalyseResponse) GetLevel2() int32 {
	if x != nil {
		return x.Level2
	}
	return 0
}

func (x *AnalyseResponse) GetLevel3() int32 {
	if x != nil {
		return x.Level3
	}
	return 0
}

// 传入训练命令
type TrainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Active bool `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
}

func (x *TrainRequest) Reset() {
	*x = TrainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_core_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainRequest) ProtoMessage() {}

func (x *TrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_core_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainRequest.ProtoReflect.Descriptor instead.
func (*TrainRequest) Descriptor() ([]byte, []int) {
	return file_pb_core_proto_rawDescGZIP(), []int{3}
}

func (x *TrainRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

// 返回训练完成标志
type TrainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` //  是否完成训练
}

func (x *TrainResponse) Reset() {
	*x = TrainResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_core_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainResponse) ProtoMessage() {}

func (x *TrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_core_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainResponse.ProtoReflect.Descriptor instead.
func (*TrainResponse) Descriptor() ([]byte, []int) {
	return file_pb_core_proto_rawDescGZIP(), []int{4}
}

func (x *TrainResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 传入的需要预测的数据结构
type Datainput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clocationinfo string `protobuf:"bytes,1,opt,name=clocationinfo,proto3" json:"clocationinfo,omitempty"` // 设备定位信息
}

func (x *Datainput) Reset() {
	*x = Datainput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_core_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Datainput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Datainput) ProtoMessage() {}

func (x *Datainput) ProtoReflect() protoreflect.Message {
	mi := &file_pb_core_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Datainput.ProtoReflect.Descriptor instead.
func (*Datainput) Descriptor() ([]byte, []int) {
	return file_pb_core_proto_rawDescGZIP(), []int{5}
}

func (x *Datainput) GetClocationinfo() string {
	if x != nil {
		return x.Clocationinfo
	}
	return ""
}

// 传入需要进行预测的告警序列
type AlertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datarequest []*Datainput `protobuf:"bytes,1,rep,name=datarequest,proto3" json:"datarequest,omitempty"` // 请求数据
}

func (x *AlertRequest) Reset() {
	*x = AlertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_core_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertRequest) ProtoMessage() {}

func (x *AlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_core_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertRequest.ProtoReflect.Descriptor instead.
func (*AlertRequest) Descriptor() ([]byte, []int) {
	return file_pb_core_proto_rawDescGZIP(), []int{6}
}

func (x *AlertRequest) GetDatarequest() []*Datainput {
	if x != nil {
		return x.Datarequest
	}
	return nil
}

// 前后交互的数据，传入参照
// 1028-9-上饶余干康山-OADM2:EMUP_F1K[00]:14
// 格式为int-int-string-string-string:string-string[]
type Dataoutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clocationinfo string `protobuf:"bytes,1,opt,name=clocationinfo,proto3" json:"clocationinfo,omitempty"`
}

func (x *Dataoutput) Reset() {
	*x = Dataoutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_core_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dataoutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dataoutput) ProtoMessage() {}

func (x *Dataoutput) ProtoReflect() protoreflect.Message {
	mi := &file_pb_core_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dataoutput.ProtoReflect.Descriptor instead.
func (*Dataoutput) Descriptor() ([]byte, []int) {
	return file_pb_core_proto_rawDescGZIP(), []int{7}
}

func (x *Dataoutput) GetClocationinfo() string {
	if x != nil {
		return x.Clocationinfo
	}
	return ""
}

// 预测结果
type AlertResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dataresponse []*Dataoutput `protobuf:"bytes,1,rep,name=dataresponse,proto3" json:"dataresponse,omitempty"` // 返回的数据数组
}

func (x *AlertResponse) Reset() {
	*x = AlertResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_core_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertResponse) ProtoMessage() {}

func (x *AlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_core_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertResponse.ProtoReflect.Descriptor instead.
func (*AlertResponse) Descriptor() ([]byte, []int) {
	return file_pb_core_proto_rawDescGZIP(), []int{8}
}

func (x *AlertResponse) GetDataresponse() []*Dataoutput {
	if x != nil {
		return x.Dataresponse
	}
	return nil
}

var File_pb_core_proto protoreflect.FileDescriptor

var file_pb_core_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0xe6, 0x01, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x53, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x6f, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x63, 0x6c, 0x6f, 0x67, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61,
	0x6c, 0x61, 0x72, 0x6d, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x63, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6e,
	0x65, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6e, 0x65, 0x69, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x75, 0x74, 0x63, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x63, 0x63, 0x75,
	0x72, 0x75, 0x74, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x63, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x6c, 0x69, 0x6e, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x6e, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x34, 0x0a, 0x0e,
	0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x62, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x92, 0x01, 0x0a, 0x0f, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x6c, 0x6c, 0x5f, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x6c, 0x6c,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x30, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x30, 0x12,
	0x16, 0x0a, 0x06, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x31, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x32, 0x12,
	0x16, 0x0a, 0x06, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x33, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x33, 0x22, 0x26, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22,
	0x29, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x31, 0x0a, 0x09, 0x44, 0x61,
	0x74, 0x61, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x63, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x3f, 0x0a,
	0x0c, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a,
	0x0b, 0x64, 0x61, 0x74, 0x61, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x52, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x32,
	0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x24, 0x0a, 0x0d,
	0x63, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x69, 0x6e,
	0x66, 0x6f, 0x22, 0x43, 0x0a, 0x0d, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x9c, 0x01, 0x0a, 0x04, 0x63, 0x6f, 0x72, 0x65,
	0x12, 0x34, 0x0a, 0x07, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x62,
	0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x13, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x05, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x12,
	0x10, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x05, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x12,
	0x10, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_core_proto_rawDescOnce sync.Once
	file_pb_core_proto_rawDescData = file_pb_core_proto_rawDesc
)

func file_pb_core_proto_rawDescGZIP() []byte {
	file_pb_core_proto_rawDescOnce.Do(func() {
		file_pb_core_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_core_proto_rawDescData)
	})
	return file_pb_core_proto_rawDescData
}

var file_pb_core_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pb_core_proto_goTypes = []interface{}{
	(*DataStruct)(nil),      // 0: pb.DataStruct
	(*AnalyseRequest)(nil),  // 1: pb.AnalyseRequest
	(*AnalyseResponse)(nil), // 2: pb.AnalyseResponse
	(*TrainRequest)(nil),    // 3: pb.TrainRequest
	(*TrainResponse)(nil),   // 4: pb.TrainResponse
	(*Datainput)(nil),       // 5: pb.Datainput
	(*AlertRequest)(nil),    // 6: pb.AlertRequest
	(*Dataoutput)(nil),      // 7: pb.Dataoutput
	(*AlertResponse)(nil),   // 8: pb.AlertResponse
}
var file_pb_core_proto_depIdxs = []int32{
	0, // 0: pb.AnalyseRequest.data:type_name -> pb.DataStruct
	5, // 1: pb.AlertRequest.datarequest:type_name -> pb.Datainput
	7, // 2: pb.AlertResponse.dataresponse:type_name -> pb.Dataoutput
	1, // 3: pb.core.Analyse:input_type -> pb.AnalyseRequest
	3, // 4: pb.core.Train:input_type -> pb.TrainRequest
	6, // 5: pb.core.Alert:input_type -> pb.AlertRequest
	2, // 6: pb.core.Analyse:output_type -> pb.AnalyseResponse
	4, // 7: pb.core.Train:output_type -> pb.TrainResponse
	8, // 8: pb.core.Alert:output_type -> pb.AlertResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_core_proto_init() }
func file_pb_core_proto_init() {
	if File_pb_core_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_core_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_core_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalyseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_core_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalyseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_core_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_core_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_core_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Datainput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_core_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_core_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dataoutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_core_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlertResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_core_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_core_proto_goTypes,
		DependencyIndexes: file_pb_core_proto_depIdxs,
		MessageInfos:      file_pb_core_proto_msgTypes,
	}.Build()
	File_pb_core_proto = out.File
	file_pb_core_proto_rawDesc = nil
	file_pb_core_proto_goTypes = nil
	file_pb_core_proto_depIdxs = nil
}
